### ISSUE TITLE
low o3 in wrfout

### ISSUE THREAD

**Issue by clin-nick** [weiwilliam/Wx-AQ_LuLab#76]
o3 is too low, while the magnitude of other species (PM2.5, CO, NO2) looks reasonable.

-- in the prepchem.log --
**+ do_ic=.false.**
+ idom=1
+ '[' 1 -le 1 ']'
+ echo 'mozbc for Domain 1:'
mozbc for Domain 1:
+ '[' 1 -eq 1 ']'
**+ do_bc=.true.**
+ sh create_emiinp_mozbc.bash /network/asrc/scratch/lulab/dg771199/WRFChem-GSIMes/2023030800/mozbc .true. .false. 1
---
We do not map Chem IC from WACCM. 
And, it seems Chem IC is not generated from the previous day's Chem fields correctly.

**Comment by weiwilliam** [comment]
@clin-nick yeah, if not first-cycle, we should use the fields from the previous cycle.
Figures below are o3 field at surface valid at 20230309 00z from GSI (wrf_inout), 6 hour forecast (wrfout_2023030818_f06), and the first wrfout (wrfout_2023030900_f00).
So fields (at least ozone) inherit from the previous cycle properly.
Low ozone concentration should be caused by other factors.

![o3_in_wrf_inout_2023030900](https://user-images.githubusercontent.com/10061966/224093033-7aca3308-9707-408d-96e7-0bdfdd636be9.png)
![o3_in_wrfout_2023030818_f06](https://user-images.githubusercontent.com/10061966/224093036-48a37751-c5c8-440b-9eb4-2f1702eafb67.png)
![o3_in_wrfout_2023030900_f00](https://user-images.githubusercontent.com/10061966/224093040-8eaeabf4-612d-4295-ae56-3dbe5de9ceb7.png)

**Comment by weiwilliam** [comment]
@dpgrogan27 chemistry field is initialized in prepchem (WRFCHEM_INPUT before).

**Comment by weiwilliam** [comment]
The problem is related to the #72 (should be prepchem). The emi/mozbc was not created properly, I'll work on this later today. @dpgrogan27 @clin-nick if you like, you can also checkout fix/prepchem to fix the problem discussed in #72 .

**Comment by dpgrogan27** [comment]
![spa_O3_2023-03-24_06%3A00%3A_NYS](https://user-images.githubusercontent.com/56127068/227408304-2c9b2ee3-31f4-401f-8cd0-29f0083b8300.png)

Fixed
